name: JediPack
version: 1.0
author: i_Jedi
main: "me.ijedi.jedipack.JediPackMain"
description: "Description here."


commands:
  ping:
    description: A test command that returns "Pong!"
    usage: /ping
  pingEnable:
    description: This does nothing besides toggling the pingCommandEnabled configuration.
    usage: /pingEnable
  testMenu:
    description: /testMenu command.
    usage: /testMenu
  testStand:
    description: /testStand command.
    usage: /testStand
  jppk:
    description: /jppk command. Tell Jedi to write some proper help text.
    usage: /jppk
