name: JediPack
version: 1.0
author: i_Jedi
main: "me.ijedi.jedipack.JediPackMain"
description: "Description here."
api-version: 1.13


commands:
  jppk:
    description: "Interact with parkour courses. Use '/jppk help' for more information."
    usage: /jppk
