name: JediPack
version: 1.0
author: i_Jedi
main: "me.ijedi.jedipack.JediPackMain"
description: "Description here."
api-version: 1.13


commands:
  parkour:
    description: "Interact with parkour courses. Use '/parkour help' for more information."
    usage: /parkour
  tabmessage:
    description: "Reloads the configuration for Tab Messages."
    usage: /tabmessage reload
  motd:
    description: "Reloads the configuration for MOTD."
    usage: /motd reload
  smite:
    description: "Smites the specified player."
    usage: /smite <player>
  signlock:
    description: "Interact with Sign Locks."
    usage: /signlock
  home:
      description: "Interact with Homes."
      usage: /home


permissions:
  jp.parkour.admin.create:
    description: "Gives permission to create a parkour course."
  jp.parkour.admin.delete:
    description: "Gives permission to delete a parkour course."
  jp.parkour.admin.start:
    description: "Gives permission to set the starting point of a parkour course."
  jp.parkour.admin.finish:
    description: "Gives permission to set the finishing point of a parkour course."
  jp.parkour.admin.edit:
    description: "Gives permission to use the menu UI to edit a parkour course."
  jp.parkour.admin.checkpoint.add:
    description: "Gives permission to add checkpoints to a parkour course."
  jp.parkour.admin.checkpoint.remove:
    description: "Gives permission to remove checkpoints from a parkour course."
  jp.parkour.user.course:
    description: "Gives permission to a player to use a parkour course."
  jp.parkour.user.restart:
    description: "Gives permission to the command '/parkour restart'."
  jp.parkour.user.checkpoint:
    description: "Gives permission to the command '/parkour checkpoint'."

  jp.tabmessage.reload:
    description: "Gives permission to the command '/tabmessage reload'."

  jp.motd.reload:
    description: "Gives permission to the command '/motd reload'."

  jp.smite:
    description: "Gives permission to the command '/smite'."

  jp.signlock.share:
    description: "Gives permission to the command '/signlock share ...'"
  jp.signlock.revoke:
    description: "Gives permission to the command '/signlock revoke ...'"
  jp.signlock.hoppers:
    description: "Gives permission to the command '/signlock hoppers ...'"
  jp.signlock.limitBypass:
    description: "Gives permission to exceed the number of allowed sign locks."
  jp.signlock.limitSet:
    description: "Gives permission to update the sign lock limit."
  jp.signlock.bypass:
    description: "Allows player to open or break any locked container."
  jp.signlock.create:
    description: "Allows player to create a sign lock."
  jp.signlock.remove:
    description: "Allows player to break a sign lock."
  jp.signlock.info:
    description: "Allows player to see info about their sing locks."

  jp.home.use:
    description: "Access /home <home>"
  jp.home.set:
    description: "Access /home set"
  jp.home.unset:
    description: "Access /home unset"
  jp.home.limit:
    description: "Access /home limit <newLimit>"
  jp.home.list:
    description: "Access /home list"