name: JediPack
version: 1.0
author: i_Jedi
main: "me.ijedi.jedipack.JediPackMain"
description: "Description here."
api-version: 1.13


commands:
  jppk:
    description: "Interact with parkour courses. Use '/jppk help' for more information."
    usage: /jppk
  jptm:
    description: "Reloads the configuration for Tab Messages."
    usage: /jptm reload
  jpmotd:
    description: "Reloads the configuration for MOTD."
    usage: /jpmotd reload
  smite:
    description: "Smites the specified player."
    usage: /smite <player>
  signlock:
    description: "Interact with Sign Locks."
    usage: /signlock


permissions:
  jp.parkour.admin.create:
    description: "Gives permission to create a parkour course."
  jp.parkour.admin.delete:
    description: "Gives permission to delete a parkour course."
  jp.parkour.admin.start:
    description: "Gives permission to set the starting point of a parkour course."
  jp.parkour.admin.finish:
    description: "Gives permission to set the finishing point of a parkour course."
  jp.parkour.admin.edit:
    description: "Gives permission to use the menu UI to edit a parkour course."
  jp.parkour.admin.checkpoint.add:
    description: "Gives permission to add checkpoints to a parkour course."
  jp.parkour.admin.checkpoint.remove:
    description: "Gives permission to remove checkpoints from a parkour course."
  jp.parkour.user.course:
    description: "Gives permission to a player to use a parkour course."
  jp.parkour.user.restart:
    description: "Gives permission to the command '/jppk restart'."
  jp.parkour.user.checkpoint:
    description: "Gives permission to the command '/jppk checkpoint'."

  jp.tabmessage.reload:
    description: "Gives permission to the command '/jptm reload'."

  jp.motd.reload:
    description: "Gives permission to the command '/jpmotd reload'."

  jp.smite:
    description: "Gives permission to the command '/jpsmite'."

  jp.signlock.share:
    description: "Gives permission to the command '/signlock share ...'"
  jp.signlock.revoke:
    description: "Gives permission to the command '/signlock revoke ...'"
  jp.signlock.hoppers:
    description: "Gives permission to the command '/signlock hoppers ...'"